# Generated by Django 5.2.4 on 2025-07-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(verbose_name='название')),
                ('data', models.CharField(verbose_name='название')),
                ('opisanie', models.TextField(verbose_name='описание')),
            ],
        ),
    ]
