# Generated by Django 5.2.4 on 2025-07-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product',
            field=models.IntegerField(blank=True, null=True, verbose_name='artikul'),
        ),
        migrations.AddField(
            model_name='product',
            name='bonus_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество бонусов'),
        ),
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.CharField(blank=True, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='страна производство'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='в наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='вес'),
        ),
    ]
