# Generated by Django 5.2.4 on 2025-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_product_bonus_count_product_brend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('volume', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.CharField()),
                ('condition', models.CharField()),
                ('gearbox', models.CharField()),
                ('color', models.CharField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('weight', models.FloatField()),
                ('brand', models.CharField(default='mercedes')),
                ('transmission', models.CharField()),
            ],
            options={
                'verbose_name': 'Моделька для машин',
            },
        ),
    ]
