# Generated by Django 5.2.4 on 2025-07-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(blank=True, choices=[('Сом', 'Сом'), ('Доллар', '$')], null=True, verbose_name='Валюта'),
        ),
    ]
